package atm_guiv2;


import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gui.java
 *
 * Created on 9/Nov/2012, 11:47:47
 */

/**
 *
 * @author 0103629
 */
 class cashManagement {

    //money related
   public double balance, amountinput, transferamount;
   public int pin, accountinput;

    //client related
   public int accountnumber;
   public String clientname;
   public int newPIN;
   boolean flag;

       // objects
    public static cashManagement client1 = new cashManagement();
    public static cashManagement client2 = new cashManagement();


    public void clientManagement() {

        client1.pin = 1234;
        client1.clientname = "Josh";
        client1.accountnumber = 1;
        client1.balance = 9000;
        client1.flag = false;

        client2.pin = 9876;
        client2.clientname = "John";
        client2.accountnumber = 2;
        client2.balance = 1000;
        client2.flag = false;
        
    }


}

public class gui extends javax.swing.JFrame {

    /** Creates new form gui */
    public gui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClientbtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addClientbtn.setText("Add clients");
        addClientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientbtnActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClientbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(loginBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClientbtn)
                    .addComponent(loginBtn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
        if (cashManagement.client1.clientname == null) {
            JOptionPane.showMessageDialog(this, "No clients added, please use the add clients button.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            
        setVisible(false);
        new Login().setVisible(true);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void addClientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientbtnActionPerformed
        // TODO add your handling code here:
        cashManagement.client1.clientManagement();
        JOptionPane.showMessageDialog(this, "Clients added.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addClientbtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientbtn;
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables

}
