/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_guiv2;

import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawLabel = new javax.swing.JLabel();
        withdrawBtn = new javax.swing.JButton();
        withdrawTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        withdrawLabel.setText("Insert amount:");

        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(withdrawLabel)
                        .addGap(18, 18, 18)
                        .addComponent(withdrawTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(withdrawBtn)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(withdrawTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawBtn)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
        try {
            
        if (cashManagement.client1.flag == true) {
            
            if (cashManagement.client1.balance < Double.parseDouble(withdrawTxt.getText())) {
                JOptionPane.showMessageDialog(this, "You don't have enough money. ", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            
            else {   
            cashManagement.client1.balance -= Double.parseDouble(withdrawTxt.getText());
        
            JOptionPane.showMessageDialog(this, "You have withdrawn: " + withdrawTxt.getText(), "Info", JOptionPane.INFORMATION_MESSAGE);
            
            setVisible(false);
            new startATM().setVisible(true);
             startATM.helloLabel.setText("Hello, " + cashManagement.client1.clientname + "!");
        }
        }
        
        else if (cashManagement.client2.flag == true) {
          if (cashManagement.client2.balance < Double.parseDouble(withdrawTxt.getText())) {
                JOptionPane.showMessageDialog(this, "You don't have enough money. ", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            
            else {   
         cashManagement.client2.balance -= Double.parseDouble(withdrawTxt.getText());
        
            JOptionPane.showMessageDialog(this, "You have withdrawn: " + withdrawTxt.getText(), "Info", JOptionPane.INFORMATION_MESSAGE);
            
            setVisible(false);
            new startATM().setVisible(true);
             startATM.helloLabel.setText("Hello, " + cashManagement.client2.clientname + "!");
        }
        }
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format. ", "Error", JOptionPane.ERROR_MESSAGE); 
            
            withdrawTxt.setText("");
        }
    }//GEN-LAST:event_withdrawBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JTextField withdrawTxt;
    // End of variables declaration//GEN-END:variables
}
