package EuroMilhoes;

import java.util.Random;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menu.java
 *
 * Created on 16/Nov/2012, 10:06:55
 */

/**
 *
 * @author 0103629
 */
public class menu extends javax.swing.JFrame {

    /** Creates new form menu */
    public menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numLabel = new javax.swing.JLabel();
        first_txt = new javax.swing.JTextField();
        second_txt = new javax.swing.JTextField();
        third_txt = new javax.swing.JTextField();
        fourth_txt = new javax.swing.JTextField();
        fifth_txt = new javax.swing.JTextField();
        starsLabel = new javax.swing.JLabel();
        firststar_txt = new javax.swing.JTextField();
        secondstar_txt = new javax.swing.JTextField();
        generateBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        numLabel.setText("Numbers");

        first_txt.setEditable(false);

        second_txt.setEditable(false);

        third_txt.setEditable(false);

        fourth_txt.setEditable(false);

        fifth_txt.setEditable(false);

        starsLabel.setText("Stars");

        firststar_txt.setEditable(false);

        secondstar_txt.setEditable(false);

        generateBtn.setText("Generate");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View keys");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(numLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(first_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firststar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(secondstar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(second_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(starsLabel)))
                        .addGap(29, 29, 29)
                        .addComponent(third_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fourth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(fifth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(generateBtn))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(numLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(second_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(third_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fifth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(starsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firststar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondstar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(generateBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(viewBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //variables
    Random gen = new Random();

    int i = 0; // numbers
    int rnd = 0;
   static int[] rndarray = new int[5];

    int j = 0; //stars
    int rndstar = 0;
   static int[] rndstararray = new int[2];

   boolean notOpen = true; //used to check if view keys window is open
   //end variables

    public void addtoView() {
        //add automatically to view
                int g = 0;
                int h = 0;

        view.showTxtArea.setText(view.showTxtArea.getText() + "Numbers -> ");
        for (g = 0; g < 5; g++) {
            view.showTxtArea.setText(view.showTxtArea.getText() + " " + rndarray[g]);
        }

            view.showTxtArea.setText(view.showTxtArea.getText() + "\n" + "Stars -> ");
        for (h = 0; h < 2; h++) {
            view.showTxtArea.setText(view.showTxtArea.getText() + " " + rndstararray[h]);
        }

            view.showTxtArea.setText(view.showTxtArea.getText() + "\n" + "-----------------------" + "\n");

//end automatically to view
    }

    public void clearText() {
        //clear
                String checker;

                checker = first_txt.getText();

                if (checker.length() > 0) {
                first_txt.setText("");
                second_txt.setText("");
                third_txt.setText("");
                fourth_txt.setText("");
                fifth_txt.setText("");

                firststar_txt.setText("");
                secondstar_txt.setText("");
                }
//end clear
    }

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:

            if (notOpen == false) {
                addtoView();
            }
        else
            {
                new view().setVisible(true);
                notOpen = false;

                addtoView();
        }
    }//GEN-LAST:event_viewBtnActionPerformed

   public void numGen() {
       //generate number
                 for (i = 0; i < 5; i++) {

                     rnd = gen.nextInt(49) + 1;

                     for (int checkifExist = 0; checkifExist < rndarray.length; checkifExist++) {
                         if (rndarray[checkifExist] == rnd) {
                             rnd = gen.nextInt(49) + 1;
                         }
                     }

                rndarray[i] = rnd;

                    }

                first_txt.setText(first_txt.getText() + rndarray[0]);
                second_txt.setText(second_txt.getText() + rndarray[1]);
                third_txt.setText(third_txt.getText() + rndarray[2]);
                fourth_txt.setText(fourth_txt.getText() + rndarray[3]);
                fifth_txt.setText(fifth_txt.getText() + rndarray[4]);
//end generate number
   }

   public void starGen() {
       //generate star
                for (j = 0; j < 2; j++) {

                    rndstar = gen.nextInt(10) + 1;

                     for (int checkifExist = 0; checkifExist < rndstararray.length; checkifExist++) {
                         if (rndstararray[checkifExist] == rndstar) {
                             rndstar = gen.nextInt(49) + 1;
                         }
                     }

                    rndstararray[j] = rndstar;
                }

                firststar_txt.setText(firststar_txt.getText() + rndstararray[0]);
                secondstar_txt.setText(secondstar_txt.getText() + rndstararray[1]);
//end generate star
   }

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
       
        clearText();

        numGen();

        starGen();

        addtoView();
    }//GEN-LAST:event_generateBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fifth_txt;
    private javax.swing.JTextField first_txt;
    private javax.swing.JTextField firststar_txt;
    private javax.swing.JTextField fourth_txt;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextField second_txt;
    private javax.swing.JTextField secondstar_txt;
    private javax.swing.JLabel starsLabel;
    private javax.swing.JTextField third_txt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

}
